import { Link } from '@tanstack/react-router'
import { NeuralOrbit } from '../components/Visuals'
import { CircuitMap, SymbolGlyph } from './SymbolGlyph'
import { challengeCount, errorsForDoor, expectedCode, solvedForDoor, symbolLabels, symbols, totalAttempts, totalErrors, type Challenge, type ChallengeRecord, type Door, type GameResult, type SymbolId } from './engine'
import type { Feedback } from './GameExperience'

function CodeRow({ code, label, muted = false }: { code: SymbolId[]; label: string; muted?: boolean }) {
  return <div><p className="mb-3 text-xs font-bold tracking-[.15em] text-mist uppercase">{label}</p><div className="flex gap-2 sm:gap-3">{code.map((symbol, index) => <div key={`${symbol}-${index}`} className={`grid size-17 place-items-center rounded-xl border sm:size-20 ${muted?'border-line bg-ink/50 text-mist':'border-cyan/45 bg-cyan/9 text-cyan'}`}><SymbolGlyph symbol={symbol} className="size-10"/></div>)}</div></div>
}

function DoorProgress({ active, open }: { active: Door; open: boolean }) {
  return <div className="flex gap-2" aria-label={`Porta ${active} de 3`}>
    {([1, 2, 3] as const).map(door => <div key={door} className={`grid size-10 place-items-center rounded-full border text-sm font-bold ${door===active ? open?'border-cyan bg-cyan text-ink':'border-cyan bg-cyan/14 text-cyan' : door<active?'border-cyan/55 text-cyan':'border-line text-mist'}`}>{door}</div>)}
  </div>
}

export function IntroScreen({ onStart }: { onStart: () => void }) {
  return <section className="grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div data-enter><p className="font-bold text-cyan">Uma experiência sobre aprender e se adaptar</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-[-.035em] sm:text-6xl">Três portas. Uma regra para descobrir.</h1><p className="mt-6 max-w-[62ch] text-lg leading-relaxed text-mist">Observe o circuito, monte códigos de três símbolos e use cada resposta para melhorar a próxima tentativa. Quando achar que aprendeu a regra, o caminho muda.</p><div className="mt-8 flex flex-wrap items-center gap-5"><button type="button" onClick={onStart} className="min-h-14 rounded-lg bg-cyan px-8 py-3.5 text-lg font-bold text-ink hover:bg-ice">Entrar no laboratório ↗</button><span className="text-sm text-mist">Cerca de 2 a 3 minutos · sem cronômetro</span></div></div><div data-enter className="circuit-pulse rounded-2xl border border-cyan/30 bg-panel/70 p-6 sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-[.18em] text-cyan uppercase">Código secreto</span><span className="text-mist">01 / 03</span></div><div className="door-lock mx-auto mt-8 grid size-27 place-items-center rounded-[2rem] border border-cyan/45 bg-cyan/8 text-cyan shadow-[0_0_55px_rgba(84,217,237,.12)]"><svg viewBox="0 0 64 64" className="size-14" fill="none" stroke="currentColor" strokeWidth="3" aria-hidden="true"><path d="M18 28V20a14 14 0 0 1 28 0v8M14 28h36v27H14z"/><circle cx="32" cy="40" r="3"/><path d="M32 43v6"/></svg></div><div className="mt-8 flex justify-center gap-3">{symbols.slice(0,3).map(symbol=><div key={symbol} className="grid size-15 place-items-center rounded-xl border border-line text-cyan"><SymbolGlyph symbol={symbol} className="size-9"/></div>)}</div><p className="mt-6 text-center text-sm text-mist">Observe · teste · ajuste</p></div></section>
}

export function InstructionScreen({ onBegin }: { onBegin: () => void }) {
  return <section className="mx-auto max-w-4xl"><h1 data-enter className="text-4xl font-bold tracking-[-.035em] sm:text-5xl">Como abrir as portas</h1><p data-enter className="mt-5 max-w-2xl text-lg leading-relaxed text-mist">Os símbolos seguem uma ordem circular. Em cada desafio, transforme os três símbolos de entrada e monte um código de saída.</p><div data-enter className="mt-8"><CircuitMap/></div><div className="mt-10 grid gap-5 sm:grid-cols-3">{[
    ['01 / Observe','Veja os três símbolos de entrada e a regra da porta.'],
    ['02 / Monte','Toque nos símbolos para preencher as três posições. Você pode apagar e tentar de novo.'],
    ['03 / Aprenda','A resposta indica quantas posições estão certas. Use essa pista na próxima tentativa.'],
  ].map(([title,description])=><div data-enter key={title} className="border-t border-line pt-5"><h2 className="text-xl font-bold text-cyan">{title}</h2><p className="mt-3 leading-relaxed text-mist">{description}</p></div>)}</div><p data-enter className="mt-8 text-sm leading-relaxed text-mist">Cada porta tem dois códigos. Há até quatro tentativas por código; se precisar, uma pista aparece. O jogo sempre permite seguir adiante.</p><button data-enter type="button" onClick={onBegin} className="mt-8 min-h-14 rounded-lg bg-cyan px-8 py-3.5 text-lg font-bold text-ink hover:bg-ice">Abrir a primeira porta</button></section>
}

export function PlayScreen({ challenge, index, draft, attempts, feedback, hintAvailable, hintShown, onAdd, onRemove, onClear, onSubmit, onHint, onNext }: {
  challenge: Challenge; index: number; draft: SymbolId[]; attempts: number; feedback: Feedback | null; hintAvailable: boolean; hintShown: boolean;
  onAdd: (symbol: SymbolId) => void; onRemove: () => void; onClear: () => void; onSubmit: () => void; onHint: () => void; onNext: () => void;
}) {
  const local = index % 2 + 1
  const changed = challenge.door === 3
  const hint = changed ? 'Experimente voltar um símbolo no circuito em vez de avançar.' : 'Cada símbolo da entrada avança uma posição no circuito. Depois da estrela, vem o círculo.'
  return <section className="mx-auto max-w-5xl"><div data-enter className="flex flex-wrap items-center justify-between gap-5 border-b border-line pb-6"><div><p className="font-bold text-cyan">Porta {challenge.door} de 3 · código {local} de 2</p><h1 className="mt-2 text-3xl font-bold tracking-[-.03em] sm:text-4xl">Monte o código de saída</h1></div><DoorProgress active={challenge.door} open={!!feedback?.solved}/></div>
    <div className="mt-6 h-1 overflow-hidden rounded-full bg-line" role="progressbar" aria-label="Progresso da experiência" aria-valuenow={index+1} aria-valuemin={1} aria-valuemax={challengeCount}><div className="h-full bg-cyan transition-[width]" style={{width:`${((index+1)/challengeCount)*100}%`}}/></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div data-enter className="space-y-5"><div className={`rule-cue rounded-xl border p-5 ${changed?'border-violet/50 bg-violet/9':'border-cyan/45 bg-cyan/9'}`}><p className="text-xs font-bold tracking-[.15em] text-mist uppercase">Regra desta porta</p><p className="mt-2 text-lg font-bold text-ice">{challenge.door===1?'Cada símbolo avança uma casa no circuito.':challenge.door===2?'A regra anterior continua. Aplique-a a uma nova entrada.':'O circuito mudou. Teste uma nova direção e observe o feedback.'}</p></div><div className="circuit-pulse"><CircuitMap uncertain={changed}/></div></div>
      <div data-enter className="rounded-2xl border border-line bg-panel p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><CodeRow code={challenge.input} label="Entrada recebida" muted/><span aria-hidden="true" className="hidden text-3xl text-cyan sm:inline">→</span></div><div className="mt-7"><p className="mb-3 text-xs font-bold tracking-[.15em] text-mist uppercase">Seu código</p><div className="flex gap-2 sm:gap-3" aria-label={`${draft.length} de 3 posições preenchidas`}>{[0,1,2].map(position=><div key={position} className={`grid size-17 place-items-center rounded-xl border sm:size-20 ${draft[position]?'border-cyan bg-cyan/9 text-cyan':'border-dashed border-line bg-ink/55 text-mist'}`}>{draft[position]?<SymbolGlyph symbol={draft[position]} className="size-10"/>:<span className="text-xl">{position+1}</span>}</div>)}</div></div><div className="mt-7 grid grid-cols-4 gap-2 sm:gap-3">{symbols.map((symbol,i)=><button key={symbol} type="button" disabled={!!feedback?.finished || draft.length===3} onClick={()=>onAdd(symbol)} className="flex min-h-22 flex-col items-center justify-center gap-1 rounded-xl border border-cyan/35 bg-ink/70 p-2 text-cyan transition-colors hover:border-cyan hover:bg-cyan/10 disabled:cursor-default disabled:opacity-50" aria-label={`Adicionar ${symbolLabels[symbol]}`}><SymbolGlyph symbol={symbol} className="size-9"/><span className="text-[.7rem] font-semibold text-ice sm:text-xs">{symbolLabels[symbol]}</span><span className="sr-only">Tecla {i+1}</span></button>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" disabled={!draft.length || !!feedback?.finished} onClick={onRemove} className="min-h-11 rounded-lg border border-line px-4 text-sm font-semibold text-mist hover:border-cyan disabled:opacity-40">Apagar último</button><button type="button" disabled={!draft.length || !!feedback?.finished} onClick={onClear} className="min-h-11 px-3 text-sm font-semibold text-mist underline underline-offset-4 disabled:opacity-40">Limpar</button><button type="button" disabled={draft.length!==3 || !!feedback?.finished} onClick={onSubmit} className="min-h-12 rounded-lg bg-cyan px-5 font-bold text-ink hover:bg-ice disabled:cursor-default disabled:opacity-40 sm:ml-auto">Testar código ↗</button></div><p className="mt-4 text-xs text-mist">Teclado: 1–4 adicionam símbolos; Backspace apaga. Tentativa {Math.min(attempts+1,4)} de 4.</p></div></div>
    {feedback && <div className={`feedback-panel mt-6 rounded-xl border p-5 sm:p-6 ${feedback.solved?'border-cyan/65 bg-cyan/9':'border-violet/60 bg-violet/9'}`} role="status"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className={`text-lg font-bold ${feedback.solved?'text-cyan':'text-violet'}`}>{feedback.solved?'Código aceito. A conexão se abriu!':feedback.revealed?'Este código foi revelado para você continuar.':`${feedback.matches} de 3 símbolos na posição certa.`}</p><p className="mt-2 leading-relaxed text-ice">{feedback.solved?'Você aplicou a regra desta porta.':feedback.revealed?'O código esperado aparece abaixo; observe como cada símbolo se transformou.':'Compare sua tentativa com a entrada e ajuste a hipótese.'}</p><p className="mt-3 text-sm font-bold text-violet">{attempts - Number(feedback.solved)} {attempts - Number(feedback.solved) === 1 ? 'erro registrado' : 'erros registrados'} neste código.</p>{feedback.revealed && <div className="mt-5"><CodeRow code={expectedCode(challenge)} label="Código revelado"/></div>}</div>{feedback.finished && <button type="button" onClick={onNext} className="min-h-13 rounded-lg bg-cyan px-6 py-3 font-bold text-ink hover:bg-ice">{index===5?'Ver resultado':'Próximo código'} ↗</button>}</div></div>}
    {!feedback?.finished && <div className="mt-6 min-h-15" role="status">{hintShown?<p className="rounded-xl border border-violet/45 bg-violet/10 p-4 font-semibold text-ice">{hint}</p>:hintAvailable?<button type="button" onClick={onHint} className="min-h-12 rounded-lg border border-violet/70 px-5 py-2 font-semibold text-violet hover:bg-violet/10">Ver uma pista</button>:<p className="text-sm text-mist">Você pode observar o circuito com calma antes de escolher.</p>}</div>}
  </section>
}

export function InterludeScreen({ door, records, onContinue }: { door: Door; records: ChallengeRecord[]; onContinue: () => void }) {
  const changed = door === 3
  const previous = (door-1) as Door
  return <section className={`phase-shift mx-auto max-w-4xl rounded-2xl border p-8 sm:p-12 ${changed?'border-violet/55 bg-violet/9':'border-cyan/40 bg-panel'}`}><p data-enter className={`font-bold ${changed?'text-violet':'text-cyan'}`}>Porta {previous} concluída</p><h1 data-enter className="mt-4 text-4xl font-bold tracking-[-.03em] sm:text-5xl">{changed?'A conexão mudou de direção.':'O padrão volta em outra porta.'}</h1><p data-enter className="mt-6 max-w-2xl text-lg leading-relaxed text-mist">{changed?'A entrada da primeira porta vai aparecer outra vez, mas a mesma resposta talvez não abra esta. Teste uma ideia nova e use o feedback.':'Você já viu como o circuito transforma símbolos. Guarde a regra e aplique-a a novas entradas.'}</p><p data-enter className="mt-6 text-sm text-ice">Na porta anterior, você encontrou {solvedForDoor(records, previous)} dos 2 códigos sem revelação.</p><button data-enter type="button" onClick={onContinue} className="mt-9 min-h-14 rounded-lg bg-cyan px-7 py-3.5 text-lg font-bold text-ink hover:bg-ice">{changed?'Investigar a mudança':'Continuar o circuito'} ↗</button></section>
}

export function ResultScreen({ result, onReset }: { result: GameResult; onReset: () => void }) {
  const solved = result.records.filter(record=>record.solved).length
  const hints = result.records.filter(record=>record.hintUsed).length
  return <section className="mx-auto max-w-5xl"><div data-enter><p className="font-bold text-cyan">As três portas foram percorridas</p><h1 className="mt-3 text-4xl font-bold tracking-[-.035em] sm:text-6xl">O que aconteceu nesta partida?</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-mist">Você montou códigos para seis circuitos. Estes números mostram somente o que aconteceu aqui.</p></div><div data-enter className="mt-10 grid gap-4 sm:grid-cols-3">{([1,2,3] as const).map(door=><div key={door} className="rounded-xl bg-panel p-6"><p className="font-bold text-cyan">Porta {door}</p><p className="font-numeric mt-5 text-3xl font-bold text-ice">{solvedForDoor(result.records,door)} <span className="text-base font-normal text-mist">de 2</span></p><p className="mt-2 text-sm text-mist">códigos encontrados sem revelação</p><p className="mt-4 text-sm font-semibold text-violet">{errorsForDoor(result.records,door)} {errorsForDoor(result.records,door)===1?'erro':'erros'} nesta porta</p></div>)}</div><p data-enter className="mt-5 text-sm leading-relaxed text-mist">Ao todo: {solved} de 6 códigos encontrados · {totalErrors(result.records)} {totalErrors(result.records)===1?'erro':'erros'} · {totalAttempts(result.records)} tentativas feitas · {hints} {hints===1?'pista aberta':'pistas abertas'}.{solved<6?' Os demais códigos foram mostrados para que a experiência pudesse continuar.':''}</p>
    <div className="mt-16 border-t border-line pt-10"><h2 data-enter className="text-3xl font-bold tracking-[-.03em] sm:text-4xl">Da tentativa à descoberta</h2><ol className="mt-10 grid gap-6 md:grid-cols-5">{[
      ['Observar','Você recebeu três símbolos e olhou a ordem do circuito.'],
      ['Imaginar','Formou uma hipótese sobre o código de saída e a guardou enquanto escolhia.'],
      ['Testar','Cada tentativa informou quantas posições estavam certas.'],
      ['Mudar','Na terceira porta, uma entrada conhecida pedia uma resposta diferente.'],
      ['Aprender','Você pôde usar o feedback para revisar sua ideia e experimentar outra regra.'],
    ].map(([title,description],i)=><li data-enter key={title} className="border-t border-line pt-5"><span className="font-numeric text-sm font-bold text-cyan">{String(i+1).padStart(2,'0')}</span><h3 className="mt-3 text-xl font-bold text-ice">{title}</h3><p className="mt-3 text-sm leading-relaxed text-mist">{description}</p></li>)}</ol></div>
    <div data-enter className="mt-14 grid gap-9 rounded-2xl border border-violet/45 bg-violet/8 p-7 sm:p-10 md:grid-cols-[.35fr_1fr]"><div className="flex justify-center"><NeuralOrbit compact/></div><div className="self-center"><h2 className="text-2xl font-bold text-ice">Como o cérebro é capaz de aprender?</h2><p className="mt-4 leading-relaxed text-mist">Ao tentar, lembrar e corrigir uma escolha, usamos atenção, memória e feedback. No cérebro, neurônios se comunicam em redes por conexões que incluem sinapses. Experiências podem alterar como circuitos funcionam ao longo do tempo — isso faz parte da neuroplasticidade. O jogo ilustra a adaptação pelo comportamento; ele não observou sinapses se formando nem mediu mudanças no seu cérebro.</p><Link to="/pesquisas" className="mt-5 inline-block font-semibold text-cyan underline underline-offset-5">Ver a explicação científica ↗</Link></div></div><p data-enter className="mt-8 max-w-4xl text-sm leading-relaxed text-mist">A experiência não mede QI, inteligência ou saúde cerebral, não oferece diagnóstico e não substitui avaliação profissional. Atenção, familiaridade, cansaço e o aparelho usado podem influenciar as escolhas.</p><div data-enter className="mt-9 flex flex-wrap items-center gap-5"><button type="button" onClick={onReset} className="min-h-14 rounded-lg bg-cyan px-7 py-3.5 text-lg font-bold text-ink hover:bg-ice">Limpar e começar para outra pessoa</button><span className="text-sm text-mist">Esta tela volta ao início automaticamente.</span></div></section>
}
