import { Link, createFileRoute } from '@tanstack/react-router'
import { useEffect, useRef } from 'react'
import gsap from 'gsap'
import { PageShell } from '../components/Layout'
import { NeuralOrbit, PathGraphic } from '../components/Visuals'
import { journey } from '../content/research'
import { CircuitMap, SymbolGlyph } from '../game/SymbolGlyph'
import { challenges } from '../game/engine'

export const Route = createFileRoute('/')({ component: Home })

function Home() {
  const hero = useRef<HTMLElement>(null)
  useEffect(() => {
    if (!hero.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    const context = gsap.context(() => {
      gsap.fromTo('.hero-reveal', { autoAlpha: 0, y: 28, filter: 'blur(9px)' }, { autoAlpha: 1, y: 0, filter: 'blur(0px)', duration: .9, stagger: .13, ease: 'power3.out' })
    }, hero)
    return () => context.revert()
  }, [])
  return <PageShell><main>
    <section ref={hero} className="mesh relative overflow-hidden px-5 sm:px-8 lg:px-12"><div className="mx-auto grid min-h-[610px] max-w-7xl items-center gap-4 py-16 lg:grid-cols-[1.07fr_.93fr] lg:py-20"><div className="relative z-10 max-w-2xl"><h1 className="hero-reveal text-[clamp(3.3rem,7vw,6rem)] leading-[1.05] font-bold tracking-[-.04em] text-ice">Como o cérebro é capaz de <span className="text-cyan">aprender?</span></h1><p className="hero-reveal mt-8 max-w-xl text-lg leading-relaxed text-mist sm:text-xl">Cada tentativa deixa uma pergunta: o que percebemos, lembramos e mudamos depois de receber uma resposta? Explore a ciência e descubra isso em duas experiências de escolhas.</p><div className="hero-reveal mt-10 flex flex-wrap gap-4"><Link to="/pesquisas" className="rounded-lg bg-cyan px-6 py-3.5 font-bold text-ink transition hover:bg-ice">Explorar a ciência ↗</Link><Link to="/jogo" className="rounded-lg border border-cyan/50 px-6 py-3.5 font-bold text-cyan transition hover:bg-cyan/10">Conhecer os jogos</Link></div></div><div className="-mx-8 flex justify-center sm:mx-0"><NeuralOrbit/></div></div><div className="pointer-events-none absolute right-0 bottom-0 left-0 h-px bg-gradient-to-r from-transparent via-cyan/45 to-transparent"/></section>
    <section className="bg-deep px-5 py-22 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-7xl"><div data-scroll className="max-w-3xl"><h2 className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">Da curiosidade à experiência.</h2><p className="mt-6 text-lg leading-relaxed text-mist">A jornada começa com neurônios e sinapses, passa por memória e feedback e termina com uma regra para testar e adaptar.</p></div><div className="mt-14 hidden md:block"><PathGraphic/></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{journey.map(([title,detail],i)=><div data-scroll key={title} className="border-t border-line pt-5"><span className="font-numeric text-sm font-bold text-cyan">{String(i+1).padStart(2,'0')}</span><h3 className="mt-3 text-xl font-bold text-ice">{title}</h3><p className="mt-2 leading-relaxed text-mist">{detail}</p></div>)}</div></div></section>
    <section className="relative overflow-hidden px-5 py-22 sm:px-8 lg:px-12 lg:py-28"><div className="pointer-events-none absolute -right-30 top-0 size-120 rounded-full bg-violet/9 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_1fr] md:items-center"><div data-scroll><h2 className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">Três portas. Uma ideia que pode mudar.</h2><p className="mt-6 max-w-[65ch] text-lg leading-relaxed text-mist">Monte códigos de símbolos, compare sua tentativa com o feedback e encontre a regra do circuito. Na última porta, uma entrada conhecida pede uma solução nova.</p><p className="mt-5 text-sm leading-relaxed text-mist">Sem cronômetro e sem classificação de pessoas. O resultado descreve apenas a sua partida.</p><Link to="/jogo/codigo" className="mt-9 inline-flex rounded-lg bg-cyan px-6 py-3.5 font-bold text-ink hover:bg-ice">Abrir Código secreto ↗</Link></div><div data-scroll className="rounded-2xl border border-line bg-panel/65 p-5 sm:p-7" aria-hidden="true"><CircuitMap/><div className="mt-6 flex justify-center gap-3">{challenges[0].input.map((symbol,i)=><div key={i} className="grid size-15 place-items-center rounded-xl border border-cyan/45 bg-cyan/8 text-cyan"><SymbolGlyph symbol={symbol} className="size-9"/></div>)}</div><p className="mt-4 text-center text-sm font-bold tracking-[.15em] text-cyan uppercase">Encontre o código de saída</p></div></div></section>
    <section className="bg-deep/85 px-5 py-22 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_1fr] md:items-center"><div data-scroll aria-hidden="true" className="order-2 flex min-h-75 items-center justify-center rounded-2xl border border-violet/35 bg-panel/70 md:order-1"><span className="text-6xl font-black tracking-[.05em] text-cyan sm:text-7xl">ROXO</span></div><div data-scroll className="order-1 md:order-2"><span className="font-bold tracking-[.16em] text-violet uppercase">Segunda experiência</span><h2 className="mt-4 text-3xl font-bold tracking-[-.03em] sm:text-5xl">E quando palavra e tinta discordam?</h2><p className="mt-6 max-w-[65ch] text-lg leading-relaxed text-mist">Em Cor ou palavra?, uma instrução orienta onde colocar a atenção. Quando ela muda, é preciso rever a escolha. Cada resposta recebe feedback.</p><Link to="/jogo/cores" className="mt-9 inline-flex rounded-lg bg-violet px-6 py-3.5 font-bold text-ink hover:bg-ice">Abrir Cor ou palavra? ↗</Link></div></div></section>
  </main></PageShell>
}
