import { Link, createFileRoute } from '@tanstack/react-router'
import { PageShell, SectionTitle } from '../components/Layout'
import { ScienceFlow } from '../components/ScienceFlow'
import { studies } from '../content/research'

export const Route = createFileRoute('/pesquisas')({ component: Research })

function Research() {
  return <PageShell className="research-glow"><main>
    <section className="mx-auto max-w-7xl px-5 pt-16 pb-18 sm:px-8 lg:px-12 lg:pt-24"><SectionTitle title="Aprender é um processo em rede.">Do sinal entre neurônios à decisão de mudar uma estratégia, há diferentes escalas para olhar a aprendizagem. A atividade da feira torna uma parte comportamental desse processo visível.</SectionTitle><div data-scroll className="mt-12 rounded-2xl border border-line bg-panel/60 p-4 sm:p-8"><ScienceFlow/></div><p className="mt-4 text-sm leading-relaxed text-mist">Diagrama conceitual. Ele não representa um registro do cérebro de quem joga.</p></section>
    <section className="bg-deep/70 px-5 py-18 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-7xl"><h2 data-scroll className="max-w-3xl text-3xl font-bold tracking-[-.03em] sm:text-5xl">Três ideias, uma pergunta maior.</h2><div className="mt-12 grid gap-6 lg:grid-cols-3"><article data-scroll className="border-t border-cyan/55 pt-6"><h3 className="text-2xl font-bold text-ice">Neurônios</h3><p className="mt-4 leading-relaxed text-mist">São células que participam do processamento de informações. Elas recebem sinais e podem enviá-los a outras células em redes.</p></article><article data-scroll className="border-t border-violet/55 pt-6"><h3 className="text-2xl font-bold text-ice">Sinapses</h3><p className="mt-4 leading-relaxed text-mist">São pontos de comunicação entre neurônios. A transmissão de sinais entre células envolve processos químicos e elétricos.</p></article><article data-scroll className="border-t border-cyan/55 pt-6"><h3 className="text-2xl font-bold text-ice">Neuroplasticidade</h3><p className="mt-4 leading-relaxed text-mist">A experiência pode modificar como circuitos neurais funcionam e se conectam. Essa capacidade de mudança participa da aprendizagem e continua possível ao longo da vida.</p></article></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:px-8 lg:px-12 lg:py-24"><h2 data-scroll className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">O que a pesquisa nos ajuda a enxergar</h2><div className="mt-12 space-y-2">{studies.map((study,i)=><article data-scroll key={study.title} className="grid gap-6 border-t border-line py-8 md:grid-cols-[.26fr_.74fr] md:py-11"><div><span className="font-numeric text-sm font-bold text-cyan">{String(i+1).padStart(2,'0')} / {study.marker}</span></div><div className="max-w-3xl"><h3 className="text-2xl font-bold tracking-[-.025em] text-ice sm:text-3xl">{study.title}</h3><p className="mt-5 text-lg leading-relaxed text-mist">{study.detail}</p><a href={study.href} target="_blank" rel="noreferrer" className="mt-5 inline-flex font-semibold text-cyan underline decoration-cyan/40 underline-offset-5 hover:decoration-cyan">Ver fonte: {study.source} ↗</a></div></article>)}</div>
      <aside data-scroll className="mt-12 grid gap-7 rounded-2xl bg-panel p-8 sm:p-11 md:grid-cols-[.6fr_1fr]"><h2 className="text-2xl font-bold tracking-[-.03em] text-ice sm:text-3xl">Leve uma hipótese para os jogos.</h2><p className="leading-relaxed text-mist">Em Código secreto, teste uma regra para transformar símbolos. Em Cor ou palavra?, escolha entre a tinta e o texto conforme a instrução. As atividades mostram escolhas e ajustes, não alterações em suas sinapses.</p></aside><Link to="/jogo" className="mt-9 inline-flex min-h-13 items-center rounded-lg bg-cyan px-6 py-3 font-bold text-ink hover:bg-ice">Escolher uma experiência ↗</Link>
    </section>
  </main></PageShell>
}
