/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as JogoRouteImport } from './routes/jogo'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as JogoCodigoRouteImport } from './routes/jogo.codigo'
import { Route as JogoCoresRouteImport } from './routes/jogo.cores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoRoute = JogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoCodigoRoute = JogoCodigoRouteImport.update({
  id: '/codigo',
  path: '/codigo',
  getParentRoute: () => JogoRoute,
} as any)
const JogoCoresRoute = JogoCoresRouteImport.update({
  id: '/cores',
  path: '/cores',
  getParentRoute: () => JogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/jogo': typeof JogoRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/referencias': typeof ReferenciasRoute
  '/resultados': typeof ResultadosRoute
  '/jogo/codigo': typeof JogoCodigoRoute
  '/jogo/cores': typeof JogoCoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/jogo': typeof JogoRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/referencias': typeof ReferenciasRoute
  '/resultados': typeof ResultadosRoute
  '/jogo/codigo': typeof JogoCodigoRoute
  '/jogo/cores': typeof JogoCoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/jogo': typeof JogoRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/referencias': typeof ReferenciasRoute
  '/resultados': typeof ResultadosRoute
  '/jogo/codigo': typeof JogoCodigoRoute
  '/jogo/cores': typeof JogoCoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipe'
    | '/jogo'
    | '/pesquisas'
    | '/referencias'
    | '/resultados'
    | '/jogo/codigo'
    | '/jogo/cores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipe'
    | '/jogo'
    | '/pesquisas'
    | '/referencias'
    | '/resultados'
    | '/jogo/codigo'
    | '/jogo/cores'
  id:
    | '__root__'
    | '/'
    | '/equipe'
    | '/jogo'
    | '/pesquisas'
    | '/referencias'
    | '/resultados'
    | '/jogo/codigo'
    | '/jogo/cores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRoute
  JogoRoute: typeof JogoRouteWithChildren
  PesquisasRoute: typeof PesquisasRoute
  ReferenciasRoute: typeof ReferenciasRoute
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/codigo': {
      id: '/jogo/codigo'
      path: '/codigo'
      fullPath: '/jogo/codigo'
      preLoaderRoute: typeof JogoCodigoRouteImport
      parentRoute: typeof JogoRoute
    }
    '/jogo/cores': {
      id: '/jogo/cores'
      path: '/cores'
      fullPath: '/jogo/cores'
      preLoaderRoute: typeof JogoCoresRouteImport
      parentRoute: typeof JogoRoute
    }
  }
}

interface JogoRouteChildren {
  JogoCodigoRoute: typeof JogoCodigoRoute
  JogoCoresRoute: typeof JogoCoresRoute
}

const JogoRouteChildren: JogoRouteChildren = {
  JogoCodigoRoute: JogoCodigoRoute,
  JogoCoresRoute: JogoCoresRoute,
}

const JogoRouteWithChildren = JogoRoute._addFileChildren(JogoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRoute,
  JogoRoute: JogoRouteWithChildren,
  PesquisasRoute: PesquisasRoute,
  ReferenciasRoute: ReferenciasRoute,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
